server:
  port: 8888
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      group-id: mail-notification-created-events
      properties:
        spring:
            json:
              trusted:
                packages: 'org.example.mailservice.data.event, org.example.coremicroservice.data.event'


